### ISSUE TITLE
librecores-ci VM should expose the 8082 port to stu45.lis.ei.tum.de (129.187.155.61)

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-backend#2]
Seems EC2 settings prohibit external connection to the machine. It would be great to add an exception for stu45.lis.ei.tum.de (129.187.155.61), which is expected to be a demo node (see https://github.com/librecores/librecores-ci/issues/12).

CC @wallento @imphil

**Comment by imphil** [comment]
all outbound traffic is allowed from ci.librecores.org, and inbound on 22 as well. So this should not be an issue

**Comment by oleg-nenashev** [comment]
Yep, but I need inbound traffic to 8082. I can setup port forwarding, but maybe it's better to just expose the port

**Comment by imphil** [comment]
and on the node machine, ci.librecores.org was banned due to too many wrong attempts (wrong username librecores-ci-bot, instead of lcci), but this ban is lifted by now.

**Comment by imphil** [comment]
And I've opened port 8082 inbound to ci.librecores.org on the AWS firewall

**Comment by oleg-nenashev** [comment]
@imphil 

> wrong username librecores-ci-bot, instead of lcci

Maybe a glitch. Checking my settings

**Comment by oleg-nenashev** [comment]
:facepalm:, but it's connected now.
@imphil Could you please login to ci.librecores.org? I'll make you a node owner then, and you will be able to manage availability of the node.

**Comment by imphil** [comment]
I've logged in, account should be created

**Comment by oleg-nenashev** [comment]
Great, please check if you have access to https://ci.librecores.org/computer/lcci-demo/ (remove, delete, etc.)

**Comment by oleg-nenashev** [comment]
This ticket is done
